### ISSUE TITLE
When we  can watch the tutorial video? 

### ISSUE THREAD

**Issue by pengzhangzhi** [ryanzhumich/Contrastive-Learning-NLP-Papers#2]
Hi! Thanks for such an insightful tutorial. I find you have not upload the tutorial video. Would you like to upload it?

**Comment by ryanzhumich** [comment]
Thanks for your interest and patience! We just published our slides and video:
slides: https://contrastive-nlp-tutorial.github.io/files/contrastive_nlp_tutorial.pdf
video: https://youtu.be/iqzJybIk4Go
