### ISSUE TITLE
Label Anchored Contrastive Learning for Language Understanding

### ISSUE THREAD

**Issue by willxxy** [ryanzhumich/Contrastive-Learning-NLP-Papers#5]
Hey, I implemented the code for the paper : Label Anchored Contrastive Learning for Language Understanding Zhenyu Zhang, Yuming Zhao, Meng Chen, Xiaodong He NAACL 2022 [[pdf]](https://arxiv.org/abs/2205.10227).
The link to it is https://github.com/willxxy/lacon

**Comment by willxxy** [comment]
Another update, I got one of the authors to review my code and they said it was a good implementation.

**Comment by ryanzhumich** [comment]
Hi, Thank you for pointing out your code.  However, the link says page not found. Could you please double check? Thanks!

**Comment by blueuuufish** [comment]
> Another update, I got one of the authors to review my code and they said it was a good implementation.

sry, the link says page not found. Could you please double check? Thanks!
